### ISSUE TITLE
Plan maintenance of this examples repo

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/examples#13]
Ideally needs a maintainer and a small group of passionate people from the community involved, like we have for pharmaverse blog.

**Comment by bms63** [comment]
You should plug this in the admiral_dev channel.  I think some folks will rise to the occasion!

**Comment by jeffreyad** [comment]
I'm willing to help with this.

**Comment by rossfarrugia** [comment]
thanks Jeff - appreciated! have it on my list to come back to this repo and do some cleanups before the holidays, so will link you then with others involved and will get this in a better position to grow from next year

**Comment by rossfarrugia** [comment]
As FYI all i have some follow-ups in Jan with few more interested groups to contribute. for now will include in description file and then will add more as and when. i'll remain with this activity as a maintainer as well, as i'm passionate to see this grow.

**Comment by rossfarrugia** [comment]
@jeffreyad i made you an admin for this repo so that you can approve/merge PRs too.

**Comment by bms63** [comment]
Yeah!!  We got some good bites from folks.  Hopefully, we can really get some them grinding on content and helping to maintain it!!  2024 is going to be awesome!!
