### ISSUE TITLE
Add Onco ADaM examples using {admiralonco}

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/examples#14]

**Comment by rossfarrugia** [comment]
@bundfussr do you think adding an onco example to https://pharmaverse.github.io/examples/ would be worth it? as i see it in the latest package release you don't really need to use {admiralonco} for any functions any more, so maybe the vignettes in the admiralonco site are sufficient. one benefit would be showing the example include metacore/metatools/xportr.

**Comment by bundfussr** [comment]
@rossfarrugia , I am not sure. What is the intention of the "examples" website? The ADSL page provides an overview how the pharmaverse packages work together without providing all ADSL derivations. This makes sense to me. However, the PK pages seem to repeat all the derivations from the admiral vignette plus the metacore/metatools/xportr steps. I wonder if we want to present how to combine the pharmaverse packages or if we want to provide the complete code for (all?, the main?) ADaM datasets.

**Comment by bundfussr** [comment]
> i guess adding an onco example here for now wouldn't add too much compared to ADSL

I agree.

> but if we were to add some KM plots or response table examples then maybe that does add value as you start to see more end-to-end examples. sorry, thinking out loud here...

If we want to add end-to-end examples for KM plots or response tables, I would present only those ADRS and ADTTE derivations which are necessary for the outputs. However, I am not sure if it adds value. The ADaMs and TLGs are produced by separate scripts anyway. Does it help to present them on the same page?

**Comment by bms63** [comment]
I'm all for Onco examples!!  I don't think the TLGs should be on the same page as this could get really long.

Perhaps some type of color theming the related TLGS, and/or a linking to the related TLGs at the end of the ADaM scripts.  Thinking this would be nice for PK related examples and as we add more examples.

Maybe a Discussion Thread should be created to help gather thoughts on how to present materials and decide on it at the next meeting?

**Comment by rossfarrugia** [comment]
thanks both! i'm thinking simple ADRS and ADTTE with minimal parameters to create something like a PFS endpoint could make sense here, and then show the PFS downstream in a table, plot, Shiny app etc in separate examples.

Good call on discussions Ben - we probably should start using those here. Will ask the team at next call.

**Comment by DavidBlairs** [comment]
@pharmaverse/Howdy. I'm constructing a plan of attack for this issue but given this content is new to myself, I wanted to outline it here first to gather some feedback. The plan, using `admiral` + `admiralonco` where applicable:

1. Generate Synthetic Data: Use the `chevron` package to generate synthetic oncology trial data that includes necessary variables for ADRS, AFTTE and PFS analysis. Ensure the data reflects typical clinical trial scenarios, such as varying time to event for ADTTE, and progression status for PFS. 

2. Develop Analysis Scripts:
  a. ADRS and ADTTE Analysis: Write R scripts using appropriate statistical methods to analyze adverse drug reactions and time to event. This could involve survival analysis techniques, Kaplan-Meier estimates for ADTTE, and descriptive statistics for ADRS.
  b. PFS Analysis: Implement an analysis for PFS, potentially using survival analysis methods. Ensure the script can handle censoring and demonstrates calculation of median PFS or other relevant metrics.

3. Visualization and Reporting: Display the results in tables, plots and potentially a Shiny app for interactive exploration. Implement color theming for related TLGs, as suggested by @bms63. 

I think a good article could be written around this, let me know if I've misunderstood something. Would we want this written in the adam folder or a sub folder specifically for adamonco?

**Comment by rossfarrugia** [comment]
thanks @DavidBlairs for taking this on! i'm happy to review the PR once ready and make sure you add yourself to the DESCRIPTION file as part of it. some replies to your points...

> 1. Generate Synthetic Data: Use the `chevron` package to generate synthetic oncology trial data that includes necessary variables for ADRS, AFTTE and PFS analysis. Ensure the data reflects typical clinical trial scenarios, such as varying time to event for ADTTE, and progression status for PFS.

No need to create your own test data.

If you're creating examples around ADRS / ADTTE here first you could use {pharmaversedtm}, e.g.  https://pharmaverse.github.io/pharmaversesdtm/main/reference/rs_onco_recist.html.

Then for TLG onco examples later could use {pharmaverseadam}, e.g. https://pharmaverse.github.io/pharmaverseadam/cran-release/reference/adrs_onco.html

> 2. Develop Analysis Scripts:
>    a. ADRS and ADTTE Analysis: Write R scripts using appropriate statistical methods to analyze adverse drug reactions and time to event. This could involve survival analysis techniques, Kaplan-Meier estimates for ADTTE, and descriptive statistics for ADRS.
>    b. PFS Analysis: Implement an analysis for PFS, potentially using survival analysis methods. Ensure the script can handle censoring and demonstrates calculation of median PFS or other relevant metrics.

Feel free to re-use extracts of https://pharmaverse.github.io/admiralonco/articles/adrs.html and https://pharmaverse.github.io/admiralonco/articles/adtte.html, and best to keep it simple for purpose of this examples site, e.g. just restrict it to whats needed for one PFS parameter.

> 3. Visualization and Reporting: Display the results in tables, plots and potentially a Shiny app for interactive exploration. Implement color theming for related TLGs, as suggested by @bms63.

Like this idea for a table and plot example, but i would hold on the shiny app example til https://github.com/pharmaverse/examples/issues/8 first.

> I think a good article could be written around this, let me know if I've misunderstood something. Would we want this written in the adam folder or a sub folder specifically for adamonco?

ADRS and ADTTE examples would be under `adam/` and the table and plot under `tlg/`. Feel free to make separate PRs for the ADaM vs the TLGs if easier as then we could pick appropriate reviewers who know each section best.

**Comment by DavidBlairs** [comment]
@rossfarrugia sounds good!
