### ISSUE TITLE
Update for admiral 1.0

### ISSUE THREAD

**Issue by jeffreyad** [pharmaverse/examples#19]
Update for admiral 1.0

**Comment by bms63** [comment]
is this just for PK or for ADSL as well?

**Comment by jeffreyad** [comment]
> is this just for PK or for ADSL as well?

@bms63 This is mainly for PK to add the `join_type` parameters in `derive_vars_joined()` but I will check ADSL as well to see if anything needs an update.

**Comment by bms63** [comment]
many thanks!!  Maybe the death cause stuff should be looked at ... not sure if that is in the e2e example.

also good to check for deprecation

**Comment by jeffreyad** [comment]
> many thanks!! Maybe the death cause stuff should be looked at ... not sure if that is in the e2e example.
> 
> also good to check for deprecation

Yes, I'll take a look at those
