### ISSUE TITLE
PK examples - use pharmaverseadam?

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/examples#21]
@jeffreyad are you ok to use pharmaverseadam for ADSL input instead of the admiral version in the 2 PK examples? 

it'd be good to have all examples going off the same test data (pharmaversesdtm and pharmaverseadam). i updated the TLG examples (in progress) to use this too.

**Comment by jeffreyad** [comment]
@rossfarrugia sure, sounds good.  Thanks!
