### ISSUE TITLE
Pinned Repos:  Replace end_to_end_examples with examples

### ISSUE THREAD

**Issue by bms63** [pharmaverse/examples#23]
Can we retire this repo and replace it with the updated version?

![image](https://github.com/pharmaverse/examples/assets/10111024/0bf65961-dabe-414f-97ec-72eff7fb8703)

**Comment by rossfarrugia** [comment]
updated

**Comment by rossfarrugia** [comment]
Will also retire the repo in Jan and take down the old site.
