### ISSUE TITLE
Include information related to installation in the introduction page

### ISSUE THREAD

**Issue by vedhav** [pharmaverse/examples#28]
Installing a bunch of open-source packages, especially when they can be interdependent with each other can cause friction for someone getting started. A good installation guide is important when showcasing examples.

**Comment by bms63** [comment]
This could be handy and a quick win!!!

**Comment by can-taslicukur** [comment]
I have submitted a Pull Request ([PR #37](https://github.com/pharmaverse/examples/pull/37)) that introduces an installation guide for running the examples locally. I would greatly appreciate it if you could review this addition and provide any feedback ❤️

**Comment by rossfarrugia** [comment]
thank you @can-taslicukur for your contribution! i just sent an invite for you to get write access to this repo in case you'd like to contribute more in future.
