### ISSUE TITLE
Add metadata folder, necessary specs in representative formats

### ISSUE THREAD

**Issue by kyleireton** [pharmaverse/examples#33]
It would be helpful to have a folder to organize the different kinds of metadata we need, primarily specs but also whatever additional pieces are needed for the pharmaverse workflow. 

We can definitely add multiple versions of specs over time as well to cover the preferred format for as many groups as possible :D

**Comment by rossfarrugia** [comment]
@kyleireton good call - would you be interested in making a PR for this? and collating any metadata from the current examples here.

**Comment by kyleireton** [comment]
Hi Ross, yes would be glad to submit the PR for pulling the metadata into one place!

**Comment by rossfarrugia** [comment]
We now have this via: https://github.com/pharmaverse/examples/tree/main/metadata
