### ISSUE TITLE
Who's who, current maintainer, the old guard

### ISSUE THREAD

**Issue by bms63** [pharmaverse/examples#38]
Was thinking about having a section listing out folks who are contributing to the site currently and those that helped with the previous site.  

![image](https://github.com/pharmaverse/examples/assets/10111024/36e70257-6b00-4fc7-bbef-c0f4b6eda360)

Be cool to have something like this to show projects we are active in! 
![image](https://github.com/pharmaverse/examples/assets/10111024/84de188a-9116-4aaf-b2d9-1cc8d355e219)

**Comment by rossfarrugia** [comment]
@bms63 could we link the DESCRIPTION file here as single place we need to maintain this info? that's also a good reminder that I need to add any others that made PRs. Can do this all together

**Comment by bms63** [comment]
yeah - I wonder if we can just source the info from the DESCRIPTION file
