### ISSUE TITLE
ADPC has the wrong number of observations 

### ISSUE THREAD

**Issue by statasaurus** [pharmaverse/examples#57]
When you check across the key variables you see there are too many observations in the ADPC example dataset 
![image](https://github.com/pharmaverse/examples/assets/55274484/6accc35a-b6d6-419f-bf09-4386bb2ec6d8)

**Comment by bms63** [comment]
@jeffreyad could you take a look at this please?

**Comment by jeffreyad** [comment]
DTYPE should be added to Key Variable list

**Comment by statasaurus** [comment]
It still looks like there is an issue. I think there was a problem with one of the merges cause you can see if you look dataset just before the last one the DOMAIN variable is sometimes from pc and ex depending on the row and there is missing corresponding to the domains

**Comment by jeffreyad** [comment]
Hi @statasaurus records from both EX and PC domains are expected.  In addition DTYPE = COPY records are added which duplicate some records from PC domain.

**Comment by jeffreyad** [comment]
Hi @statasaurus I'm closing this issue as I think it is resolved.  Let me know if you still have any questions.  Thanks!
