### ISSUE TITLE
Bug in ADaM ADSL example

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/examples#76]
The following result from the ADaM ADSL webpage doesn't look as expected.
![image](https://github.com/user-attachments/assets/44acb17b-607c-4491-9c2b-1c49aeff74ee)

By the way, there is a typo in the TOC:
![image](https://github.com/user-attachments/assets/9de67335-d496-436f-aeff-40c5a2b2ad1c)

There are two typos in the following comment:
![image](https://github.com/user-attachments/assets/dd2610ab-e4e8-4648-a0a2-e50e198b0093)

**Comment by rossfarrugia** [comment]
thanks Stefan - i'll take a look this week
