### ISSUE TITLE
Safety Shiny app example

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/examples#8]
Create a Shiny visualization of the demographic output example shared here to allow for interactive exploration

**Comment by rossfarrugia** [comment]
@pawelru mentioned: interactive part needs to wait as it is under heavy refactor right now

**Comment by rossfarrugia** [comment]
Ignore my commits above - they were meant to tag #38 instead of this issue. my mistake!

**Comment by rossfarrugia** [comment]
@pawelru is now a good time to get this Shiny example added to our examples site? @DavidBlairs is interested in adding an onco KM plot Shiny example too.

**Comment by pawelru** [comment]
Please give me some time. I'm experimenting with shinylive right now and if succeed we can embed a working app instead of just a code. But I still need some time to make it good.
